export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#8781ff',
        'secondary-fixed': '#55fcd0',
        'surface-container-high': '#262744',
        'on-primary-fixed-variant': '#3622ca',
        'secondary': '#41eec2',
        'on-secondary-fixed': '#002118',
        'inverse-on-surface': '#2d2e4b',
        'outline-variant': '#464555',
        'surface-container': '#1c1d39',
        'on-tertiary-container': '#3e2400',
        'secondary-fixed-dim': '#28dfb5',
        'background': '#0f102c',
        'on-primary-fixed': '#100069',
        'secondary-container': '#00d1a7',
        'primary-fixed': '#e3dfff',
        'error': '#ffb4ab',
        'surface-dim': '#0f102c',
        'surface-container-low': '#181934',
        'on-background': '#e1e0ff',
        'on-secondary-fixed-variant': '#00513f',
        'on-tertiary': '#472a00',
        'outline': '#918fa1',
        'surface': '#0f102c',
        'surface-bright': '#363654',
        'primary': '#c4c0ff',
        'on-error': '#690005',
        'surface-tint': '#c4c0ff',
        'tertiary': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-secondary': '#00382b',
        'surface-container-lowest': '#0a0b26',
        'tertiary-container': '#ca8100',
        'surface-container-highest': '#31324f',
        'inverse-primary': '#4f44e2',
        'on-surface-variant': '#c7c4d8',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#c4c0ff',
        'surface-variant': '#31324f',
        'on-secondary-container': '#005441',
        'on-surface': '#e1e0ff',
        'inverse-surface': '#e1e0ff',
        'error-container': '#93000a',
        'on-primary-container': '#1b0091',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary': '#2000a4',
        'on-tertiary-fixed-variant': '#653e00',
        'tertiary-fixed': '#ffddb8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'xs': '4px',
        'base': '8px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
